# Generated by Django 3.2.18 on 2023-04-14 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCategoryGroupName', models.CharField(max_length=200)),
                ('ProductCategoryGroupimg', models.CharField(max_length=200)),
                ('ProductCategoryLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('bolDisplay', models.IntegerField(default=1)),
            ],
        ),
    ]
