# Generated by Django 3.2.18 on 2023-04-05 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCategoryName', models.CharField(max_length=200)),
                ('ProductCategoryDesc1', models.CharField(max_length=1000)),
                ('ProductCategoryDesc2', models.CharField(max_length=1000)),
                ('ProductCategoryDesc3', models.CharField(max_length=1000)),
                ('ProductCategoryFeatures', models.CharField(max_length=1000)),
                ('ProductCategoryAddInfo', models.CharField(max_length=1000)),
                ('ProductCategoryimg', models.CharField(max_length=400)),
                ('ProductCategoryLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('bolDisplay', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCategoryGroupName', models.CharField(max_length=200)),
                ('ProductCategoryGroupimg', models.CharField(max_length=200)),
                ('ProductCategoryLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('bolDisplay', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductBrand', models.CharField(max_length=200)),
                ('ProductCost', models.FloatField()),
                ('Productimg', models.CharField(max_length=400)),
                ('ProductScore', models.IntegerField()),
                ('ProductScoreSummary', models.CharField(max_length=1000)),
                ('ProductPros', models.CharField(max_length=400)),
                ('ProductCons', models.CharField(max_length=400)),
                ('ProductLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('bolDisplay', models.IntegerField(default=1)),
                ('ProductCategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='ProductCategoryGroupName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategorygroup'),
        ),
    ]
