# Generated by Django 3.2.18 on 2023-04-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productcategorytestlogic'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='ProductDesc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
