# Generated by Django 3.2.18 on 2023-04-14 14:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productlist_productlistsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NavCatName', models.CharField(max_length=200)),
                ('LastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeatureName', models.CharField(max_length=200)),
                ('FeatureDesc', models.CharField(blank=True, max_length=1000)),
                ('FeatureLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('ProductCategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='NavSubCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NavSubCatName', models.CharField(max_length=200)),
                ('LastUpdated', models.DateTimeField(auto_now_add=True)),
                ('ArticleCategoryimg', models.CharField(blank=True, max_length=200, null=True)),
                ('NavCatName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navcat')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleTagName', models.CharField(max_length=200)),
                ('LastUpdated', models.DateTimeField(auto_now_add=True)),
                ('NavSubCatName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navsubcat')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleName', models.CharField(max_length=200)),
                ('Articleimg', models.CharField(blank=True, max_length=200, null=True)),
                ('ArticleBody', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('LastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('ArticleTagName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.articletag')),
                ('NavSubCatName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navsubcat')),
            ],
        ),
    ]
