# Generated by Django 3.2.18 on 2023-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productlist_productdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='AmazonLink',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
