# Generated by Django 3.2.18 on 2023-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productlist_amazonlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='AmazonStar',
            field=models.FloatField(default=0),
        ),
    ]
