# Generated by Django 3.2.18 on 2023-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productlist_amazonstar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategorytestlogic',
            name='FeatureWeight',
        ),
        migrations.AlterField(
            model_name='productcategorytestlogic',
            name='FeatureDesc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='productcategorytestlogic',
            name='FeatureScore',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='AmazonStar',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='ProductCons',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='ProductDesc',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='ProductPros',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='ProductScore',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='ProductScoreSummary',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='Productimg',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
