# Generated by Django 3.2.18 on 2023-04-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230406_2245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategoryTestLogic',
            new_name='ProductCategoryFeature',
        ),
    ]
