# Generated by Django 3.2.18 on 2023-04-24 21:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_articletag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleName', models.CharField(max_length=200)),
                ('Articleimg', models.CharField(blank=True, max_length=200, null=True)),
                ('ArticleBody', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('LastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('ArticleTagName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.articletag')),
                ('NavSubCatName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navsubcat')),
            ],
        ),
    ]
