# Generated by Django 3.2.18 on 2023-04-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_productcategorytestlogic_productcategoryfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategoryfeature',
            name='FeatureScore',
        ),
    ]
