# Generated by Django 3.2.18 on 2023-04-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_productcategoryfeature_featurescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='ProductCons',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='ProductPros',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='ProductScore',
        ),
        migrations.AddField(
            model_name='productlist',
            name='ProductListSubCategory',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
