# Generated by Django 3.2.18 on 2023-05-09 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productcategoryfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryMasterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCategoryMasterGroupName', models.CharField(max_length=200)),
                ('ProductCategoryLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('bolDisplay', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='productcategorygroup',
            name='ProductCategoryGroupimg',
        ),
        migrations.AddField(
            model_name='productcategorygroup',
            name='ProductCategoryMasterGroupName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productcategorymastergroup'),
        ),
    ]
