# Generated by Django 3.2.18 on 2023-04-10 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230410_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategoryName', models.CharField(max_length=400)),
                ('ProductListSubCategoryLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='ProductListSubCategory',
        ),
    ]
