# Generated by Django 3.2.18 on 2023-04-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230410_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='ProductListSubCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.productlistsubcategory'),
        ),
    ]
