# Generated by Django 3.2.18 on 2023-05-11 16:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230509_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryText',
            fields=[
                ('ProductCategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.productcategory')),
                ('Text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('LastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
