# Generated by Django 3.2.18 on 2023-04-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productlist_productlistsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlistsubcategory',
            name='ProductCategoryName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
        ),
    ]
