# Generated by Django 3.2.18 on 2023-04-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productlistsubcategory_productcategoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistsubcategory',
            name='ProductCategoryName',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
        ),
    ]
