# Generated by Django 3.2.18 on 2023-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_productlistsubcategory_productcategoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='ProductCategoryAddInfo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
