# Generated by Django 3.2.18 on 2023-04-11 21:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_productcategory_productcategoryaddinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NavCatName', models.CharField(max_length=200)),
                ('LastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavSubCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NavSubCatName', models.CharField(max_length=200)),
                ('LastUpdated', models.DateTimeField(auto_now_add=True)),
                ('NavCatName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navcat')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleName', models.CharField(max_length=200)),
                ('ArticleSectionCount', models.IntegerField(default=1, max_length=200)),
                ('ArticleBody', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('LastUpdated', models.DateTimeField(auto_now_add=True)),
                ('NavSubCatName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navcat')),
            ],
        ),
    ]
