# Generated by Django 3.2.18 on 2023-04-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_article_navcat_navsubcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='navsubcat',
            name='ArticleCategoryimg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
