# Generated by Django 3.2.18 on 2023-04-11 23:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_navsubcat_articlecategoryimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ArticleSectionCount',
        ),
        migrations.AddField(
            model_name='article',
            name='Articleimg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='LastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleTagName', models.CharField(max_length=200)),
                ('LastUpdated', models.DateTimeField(auto_now_add=True)),
                ('NavSubCatName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navcat')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleTagName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.articletag'),
        ),
    ]
