# Generated by Django 3.2.18 on 2023-04-13 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_articletag_navsubcatname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='NavSubCatName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navsubcat'),
        ),
    ]
